import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Shared Item/Navbar";



const poppins = Poppins({
  subsets: ["latin"],
    weight: ["400", "500", "600", "700"], 
});

export const metadata = {
  title: "QurbanirHat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        
        </body>
    </html>
  );
}
